services:
  report-service-database:
    container_name: report-service-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: contacts_app
      POSTGRES_PASSWORD: contacts_app_pass
      POSTGRES_ROOT_PASSWORD: contacts_app_pass
      POSTGRES_PORT: 54322
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - contacts_app_network
  report-service-queue:
    container_name: report-service-queue
    image: rabbitmq:4.0.5-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: contacts_app
      RABBITMQ_DEFAULT_PASS: contacts_app_pass
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - contacts_app_network
