services:
  contact-service-database:
    extends:
      file: ./contact/docker-compose.yml
      service: contact-service-database
  report-service-database:
    extends:
      file: ./report/docker-compose.yml
      service: report-service-database
  report-service-queue:
    extends:
      file: ./report/docker-compose.yml
      service: report-service-queue

networks:
  contacts_app_network:
    driver: bridge
